name: author-testing

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    container:
      image: perldocker/perl-tester:5.42

    steps:
      - uses: actions/checkout@v6
      - run: perl -V
      - name: Install Author Dependencies
        run: dzil authordeps | cpm install -g --show-build-log-on-failure -
      - name: Install Dependencies
        run: dzil listdeps | cpm install -g --show-build-log-on-failure -
      - name: dzil test
        run: dzil test
